KEY_TYPE =  'type'
KEY_INPUT_P1_JNTS =  'input_p1_jnts_list' 
KEY_INPUT_P2_JNTS =  'input_p2_jnts_list' 
KEY_REFINE_P1_JNTS =  'refine_p1_jnts_list' 
KEY_REFINE_P2_JNTS =  'refine_p2_jnts_list:'
KEY_GT_P1_JNTS =  'gt_p1_jnts_list'
KEY_GT_P2_JNTS =  'gt_p2_jnts_list'
KEY_PSEUDO_GT_P1_JNTS = 'pseudo_gt_p1_jnts_list'
KEY_PSEUDO_GT_P2_JNTS = 'pseudo_gt_p2_jnts_list'
KEY_REFINE_PSEUDO_GT_P1_JNTS = 'full_refine_pseudo_gt_p1_15fps_jnts_list'
KEY_REFINE_PSEUDO_GT_P2_JNTS = 'full_refine_pseudo_gt_p2_15fps_jnts_list'

KEY_ORIGINAL_OBJ_VERTS =  'original_obj_verts_list' 
KEY_FILTERED_OBJ_VERTS =  'filtered_obj_verts_list' 
KEY_OBJ_FACES =  'obj_faces_list' 

KEY_NUM_FRAMES =  'num_frames' 
KEY_START =  'start' 
KEY_END =  'end' 
KEY_CAM_T =  'cam_T'

TYPE_PRED =  'pred'
TYPE_GT =  'pseud_gt'

OUTPUT_DIR = 'output'
OBJ_P1_INPUT = 'input_p1'
OBJ_P2_INPUT =  'input_p2'
OBJ_P1_REFINE = 'refine_p1'
OBJ_P2_REFINE =  'refine_p2'
OBJ_GT_P1 = 'gt_p1'
OBJ_GT_P2 =  'gt_p2'
OBJ_PSEUDO_GT_P1 = 'pseudo_gt_p1'
OBJ_PSEUDO_GT_P2 =  'pseudo_gt_p2'
OBJ_REFINE_PSEUDO_GT_P1 = 'refine_pseudo_gt_p1'
OBJ_REFINE_PSEUDO_GT_P2 =  'refine_pseudo_gt_p2'

OBJ_OBJ_ORIGINAL = 'original_obj'
OBJ_OBJ_FILTERED = 'filtered_obj'

CACHE_DIR = 'cache'
CACHE_SUFFIX = '_converters.pkl'

INFO_ROOT_LOC_P1 = 'root_loc1'
INFO_ROOT_LOC_P2 = 'root_loc2'
INFO_TYPE = 'type'
INFO_FILE_NAME = 'info.npy'
INFO_CAM = 'cam'

PRIM_FILE_NAME = 'prim.npz'

INTERPOLATE = 2.0

VIDEO_DIR = "video"
BLENDER_PATH = "blender/scene.blend"

TARGET_FLAG_NONE = 0
TARGET_FLAG_INPUT = 1
TARGET_FLAG_REFINE = 2
TARGET_FLAG_GT = 3
TARGET_FLAG_PSEUDO_GT = 4
TARGET_FLAG_REFINE_PSEUDO_GT = 5
TARGET_FLAG_WOPOSE = 6
TARGET_FLAG_WOIG = 7
TARGET_FLAG_WOPROX = 8
TARGET_FLAG_WOCONTACT = 9

key_path_map = {
  KEY_INPUT_P1_JNTS: OBJ_P1_INPUT,
  KEY_INPUT_P2_JNTS: OBJ_P2_INPUT,
  KEY_ORIGINAL_OBJ_VERTS: OBJ_OBJ_ORIGINAL,
  KEY_REFINE_P1_JNTS: OBJ_P1_REFINE,
  KEY_REFINE_P2_JNTS: OBJ_P2_REFINE,
  KEY_FILTERED_OBJ_VERTS: OBJ_OBJ_FILTERED,
  KEY_GT_P1_JNTS: OBJ_GT_P1,
  KEY_GT_P2_JNTS: OBJ_GT_P2,
  KEY_PSEUDO_GT_P1_JNTS: OBJ_PSEUDO_GT_P1,
  KEY_PSEUDO_GT_P2_JNTS: OBJ_PSEUDO_GT_P2,
  KEY_REFINE_PSEUDO_GT_P1_JNTS: OBJ_REFINE_PSEUDO_GT_P1,
  KEY_REFINE_PSEUDO_GT_P2_JNTS: OBJ_REFINE_PSEUDO_GT_P2
}

keys_to_render_per_flag = { # object should come first
  TARGET_FLAG_NONE: [KEY_ORIGINAL_OBJ_VERTS],
  TARGET_FLAG_INPUT: [KEY_ORIGINAL_OBJ_VERTS, KEY_INPUT_P1_JNTS, KEY_INPUT_P2_JNTS],
  TARGET_FLAG_REFINE: [KEY_FILTERED_OBJ_VERTS, KEY_REFINE_P1_JNTS, KEY_REFINE_P2_JNTS],
  TARGET_FLAG_GT: [KEY_ORIGINAL_OBJ_VERTS, KEY_GT_P1_JNTS, KEY_GT_P2_JNTS],
  TARGET_FLAG_PSEUDO_GT: [KEY_ORIGINAL_OBJ_VERTS, KEY_PSEUDO_GT_P1_JNTS, KEY_PSEUDO_GT_P2_JNTS],
  TARGET_FLAG_REFINE_PSEUDO_GT: [KEY_FILTERED_OBJ_VERTS, KEY_REFINE_PSEUDO_GT_P1_JNTS, KEY_REFINE_PSEUDO_GT_P2_JNTS],
  TARGET_FLAG_WOPOSE: [KEY_FILTERED_OBJ_VERTS, KEY_REFINE_PSEUDO_GT_P1_JNTS, KEY_REFINE_PSEUDO_GT_P2_JNTS],
  TARGET_FLAG_WOIG: [KEY_FILTERED_OBJ_VERTS, KEY_REFINE_PSEUDO_GT_P1_JNTS, KEY_REFINE_PSEUDO_GT_P2_JNTS],
  TARGET_FLAG_WOPROX: [KEY_FILTERED_OBJ_VERTS, KEY_REFINE_PSEUDO_GT_P1_JNTS, KEY_REFINE_PSEUDO_GT_P2_JNTS],
  TARGET_FLAG_WOCONTACT: [KEY_FILTERED_OBJ_VERTS, KEY_REFINE_PSEUDO_GT_P1_JNTS, KEY_REFINE_PSEUDO_GT_P2_JNTS],
}

video_name_per_flag = {
    TARGET_FLAG_NONE: "obj_only",
    TARGET_FLAG_INPUT: "input", 
    TARGET_FLAG_REFINE: "refine",
    TARGET_FLAG_GT: "gt",
    TARGET_FLAG_PSEUDO_GT: "gt_input",
    TARGET_FLAG_REFINE_PSEUDO_GT: "all",
    TARGET_FLAG_WOCONTACT: "wocontact",
    TARGET_FLAG_WOPROX: "woprox", 
    TARGET_FLAG_WOIG: "woig",
    TARGET_FLAG_WOPOSE: "wopose"
}

keys_to_process_per_flag = {
  'default': [KEY_INPUT_P1_JNTS, KEY_INPUT_P2_JNTS, KEY_REFINE_P1_JNTS, KEY_REFINE_P2_JNTS, KEY_ORIGINAL_OBJ_VERTS, KEY_FILTERED_OBJ_VERTS],
  'gt': [KEY_INPUT_P1_JNTS, KEY_INPUT_P2_JNTS, KEY_REFINE_P1_JNTS, KEY_REFINE_P2_JNTS, KEY_GT_P1_JNTS, KEY_GT_P2_JNTS, KEY_ORIGINAL_OBJ_VERTS, KEY_FILTERED_OBJ_VERTS],
  'ab_all': [KEY_GT_P1_JNTS, KEY_GT_P2_JNTS, KEY_PSEUDO_GT_P1_JNTS, KEY_PSEUDO_GT_P2_JNTS, KEY_REFINE_PSEUDO_GT_P1_JNTS, KEY_REFINE_PSEUDO_GT_P2_JNTS, KEY_ORIGINAL_OBJ_VERTS, KEY_FILTERED_OBJ_VERTS],
  'ab_wo': [KEY_REFINE_PSEUDO_GT_P1_JNTS, KEY_REFINE_PSEUDO_GT_P2_JNTS, KEY_ORIGINAL_OBJ_VERTS, KEY_FILTERED_OBJ_VERTS],
}