JOINT_GLOBAL = 0
JOINT_LEFT_HIP = 1
JOINT_RIGHT_HIP = 2
JOINT_SPINE1 = 3
JOINT_LEFT_KNEE = 4
JOINT_RIGHT_KNEE = 5
JOINT_SPINE2 = 6
JOINT_LEFT_ANKLE = 7
JOINT_RIGHT_ANKLE = 8
JOINT_SPINE3 = 9
JOINT_LEFT_TOE = 10
JOINT_RIGHT_TOE = 11
JOINT_NECK = 12
JOINT_LEFT_COLLAR = 13
JOINT_RIGHT_COLLAR = 14
JOINT_HEAD = 15
JOINT_LEFT_SHOULDER = 16
JOINT_RIGHT_SHOULDER = 17
JOINT_LEFT_ELBOW = 18
JOINT_RIGHT_ELBOW = 19
JOINT_LEFT_WRIST = 20
JOINT_RIGHT_WRIST = 21
JOINT_LEFT_PALM = 22
JOINT_RIGHT_PALM = 23

BONE_SPINE1 = 0
BONE_LEFT_THIGH = 1
BONE_RIGHT_THIGH = 2
BONE_SPINE2 = 3
BONE_LEFT_SHANK = 4
BONE_RIGHT_SHANK = 5
BONE_SPINE3 = 6
BONE_LEFT_FOOT = 7
BONE_RIGHT_FOOT = 8
BONE_NECK = 9
BONE_HEAD = 10
BONE_LEFT_SHOULDER = 11
BONE_RIGHT_SHOULDER = 12
BONE_LEFT_UPPER_ARM = 13
BONE_RIGHT_UPPER_ARM = 14
BONE_LEFT_LOWER_ARM = 15
BONE_RIGHT_LOWER_ARM = 16
BONE_LEFT_HAND = 17
BONE_RIGHT_HAND = 18


bone_pair = {
  BONE_SPINE1: [JOINT_GLOBAL, JOINT_SPINE1],
  BONE_LEFT_THIGH: [JOINT_LEFT_HIP, JOINT_LEFT_KNEE],
  BONE_RIGHT_THIGH: [JOINT_RIGHT_HIP, JOINT_RIGHT_KNEE],
  BONE_SPINE2: [JOINT_SPINE1, JOINT_SPINE2],
  BONE_LEFT_SHANK: [JOINT_LEFT_KNEE, JOINT_LEFT_ANKLE],
  BONE_RIGHT_SHANK: [JOINT_RIGHT_KNEE, JOINT_RIGHT_ANKLE],
  BONE_SPINE3: [JOINT_SPINE2, JOINT_SPINE3],
  BONE_LEFT_FOOT: [JOINT_LEFT_ANKLE, JOINT_LEFT_TOE],
  BONE_RIGHT_FOOT: [JOINT_RIGHT_ANKLE, JOINT_RIGHT_TOE],
  BONE_NECK: [JOINT_SPINE3, JOINT_NECK],
  BONE_HEAD: [JOINT_NECK, JOINT_HEAD],
  BONE_LEFT_SHOULDER: [JOINT_LEFT_COLLAR, JOINT_LEFT_SHOULDER],
  BONE_RIGHT_SHOULDER: [JOINT_RIGHT_COLLAR, JOINT_RIGHT_SHOULDER],
  BONE_LEFT_UPPER_ARM: [JOINT_LEFT_SHOULDER, JOINT_LEFT_ELBOW],
  BONE_RIGHT_UPPER_ARM: [JOINT_RIGHT_SHOULDER, JOINT_RIGHT_ELBOW],
  BONE_LEFT_LOWER_ARM: [JOINT_LEFT_ELBOW, JOINT_LEFT_WRIST],
  BONE_RIGHT_LOWER_ARM: [JOINT_RIGHT_ELBOW, JOINT_RIGHT_WRIST],
  BONE_LEFT_HAND: [JOINT_LEFT_WRIST, JOINT_LEFT_PALM],
  BONE_RIGHT_HAND: [JOINT_RIGHT_WRIST, JOINT_RIGHT_PALM],
}

joint_radii = {
  JOINT_GLOBAL: 0.04,  # Global
  JOINT_LEFT_HIP: 0.07,  # Left hip
  JOINT_RIGHT_HIP: 0.07,  # Right hip
  JOINT_SPINE1: 0.04,  # Spine1
  JOINT_LEFT_KNEE: 0.05,  # Left knee
  JOINT_RIGHT_KNEE: 0.05,  # Right knee
  JOINT_SPINE2: 0.04,  # Spine2
  JOINT_LEFT_ANKLE: 0.05,  # Left ankle
  JOINT_RIGHT_ANKLE: 0.05,  # Right ankle
  JOINT_SPINE3: 0.04,  # Spine3
  JOINT_LEFT_TOE: 0.05, # Left toe
  JOINT_RIGHT_TOE: 0.05, # Right toe
  JOINT_NECK: 0.04, # Neck
  JOINT_LEFT_COLLAR: 0.05, # Left collar
  JOINT_RIGHT_COLLAR: 0.05, # Right collar
  JOINT_HEAD: 0.08, # Head
  JOINT_LEFT_SHOULDER: 0.05, # Left shoulder
  JOINT_RIGHT_SHOULDER: 0.05, # Right shoulder
  JOINT_LEFT_ELBOW: 0.03, # Left elbow
  JOINT_RIGHT_ELBOW: 0.03, # Right elbow
  JOINT_LEFT_WRIST: 0.03, # Left wrist
  JOINT_RIGHT_WRIST: 0.03, # Right wrist
  JOINT_LEFT_PALM: 0.05, # Left palm
  JOINT_RIGHT_PALM: 0.05  # Right palm
}

bone_radius = {
  BONE_SPINE1: 0.04,
  BONE_LEFT_THIGH: 0.05,
  BONE_RIGHT_THIGH: 0.05,
  BONE_SPINE2: 0.04,
  BONE_LEFT_SHANK: 0.05,
  BONE_RIGHT_SHANK: 0.05,
  BONE_SPINE3: 0.0,
  BONE_LEFT_FOOT: 0.05,
  BONE_RIGHT_FOOT: 0.05,
  BONE_NECK: 0.04,
  BONE_HEAD: 0.03,
  BONE_LEFT_SHOULDER: 0.05,
  BONE_RIGHT_SHOULDER: 0.05,
  BONE_LEFT_UPPER_ARM: 0.03,
  BONE_RIGHT_UPPER_ARM: 0.03,
  BONE_LEFT_LOWER_ARM: 0.03,
  BONE_RIGHT_LOWER_ARM: 0.03,
  BONE_LEFT_HAND: 0.03,
  BONE_RIGHT_HAND: 0.03,
}